/*
 * ROBOT_cfg.h
 *
 *  Created on: Aug 18, 2022
 *      Author: Ibrahem
 */

#ifndef APP_ROBOT_ROBOT_CFG_H_
#define APP_ROBOT_ROBOT_CFG_H_


#define  FRONT_RIGHT_MOTOR_PORT			DIO_PORTA
#define  FRONT_RIGHT_MOTOR_PIN1			DIO_PIN0
#define  FRONT_RIGHT_MOTOR_PIN2			DIO_PIN1


#define  FRONT_LEFT_MOTOR_PORT			DIO_PORTA
#define  FRONT_LEFT_MOTOR_PIN1			DIO_PIN3
#define  FRONT_LEFT_MOTOR_PIN2			DIO_PIN4

#define  REAR_RIGHT_MOTOR_PORT			DIO_PORTA
#define  REAR_RIGHT_MOTOR_PIN1			DIO_PIN5
#define  REAR_RIGHT_MOTOR_PIN2			DIO_PIN6

#define  REAR_LEFT_MOTOR_PORT			DIO_PORTB
#define  REAR_LEFT_MOTOR_PIN1			DIO_PIN1
#define  REAR_LEFT_MOTOR_PIN2 			DIO_PIN2
#endif /* APP_ROBOT_ROBOT_CFG_H_ */
